# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['bilibili-ai-client-gui'],
    binaries=[],
    datas=[
        ('bilibili-ai-client-gui/whisper_model', 'whisper_model'),
    ],
    hiddenimports=[
        'loguru',
        'httpx',
        'aiohttp',
        'aiosignal',
        'yarl',
        'multidict',
        'frozenlist',
        'attr',
        'async_timeout',
        'charset_normalizer',
        'idna',
        'sniffio',
        'anyio',
        'sys',
        'pathlib',
        'sqlite3',
        'config',
        'database',
        'message_poller',
        'webhook_server',
        'openclaw_trigger',
        'mcp_server',
        'mcp',
        'mcp.server',
        'mcp.types',
        'utils.logger',
        'utils.subtitle_extractor',
        'gui.main_window',
        'bilibili_login',
        'flask',
        'qrcode',
        'PIL',
        'webbrowser',
        'yt_dlp',
        'faster_whisper',
        'ctranslate2',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='BilibiliAIClient',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
